### ISSUE TITLE
I need help of compile

### ISSUE THREAD

**Issue by HanalogInstruments** [rpeyron/plugin-gimp-fourier#1]
Hi,

Can i compile the plugin of GIMP on windows and and run it without GIMP to add on my software?

**Comment by rpeyron** [comment]
Hello,
As the code of the plugin heavily relies on the GIMP library, it won't work out of the box in another software. Depending on the software you intend to use, you may be able to rewrite parts of the plugin to replace references to the GIMP library with the one of the target software.
Hope this helps
