### ISSUE TITLE
The plugin does not work without the Internet.

### ISSUE THREAD

**Issue by hhrhhr** [rpeyron/plugin-gimp-fourier#6]
GIMP 2.10.32, Windows 10 (19041)
When I try to use the plugin without Internet access, it crashes with this message:

_Plug-in crashed: "fourier.exe"
(D:\Users\*****\AppData\Roaming\GIMP\2.10\plug-ins\fourier.exe)
The dying plug-in may have messed up GIMP's internal state. You may want to save your images and restart GIMP to be on the safe side._

Here is the entry in the local firewall:
`fourier.exe, 204.79.197.219, 80 (http), tcp, Outbound`

The most interesting thing is that the plugin worked fine for 2-3 days, it only started trying to access the Internet now.

MD5 checksums:
```
cea7e6b5b514bc9ab675e4f4608ffd0e *libfftw3-3.dll
fd08c9dcc51552903622d81d7a96ae30 *fourier.exe
```

**Comment by rpeyron** [comment]
Hello, this is very strange, I confirm that the plugin does not require any internet access. 

I have just tested with the exact configuration you gave on a fresh VM and the plugin works fine without internet access (and no strange network calls observed)

The md5 listed are OK, but maybe the network calls are done in the DLL used by the fourier.exe process. You may identify those DLL with a tool like Process Explorer (https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer), with View / Show Lower Pane / DLLs ; and check all signatures are OK. 

From what you report, I guess you should check your computer against viruses/malwares.

**Comment by hhrhhr** [comment]
My problem is reproduced like this:

1. File - New - Ok
2. **Make a selection** on the current layer
3. Filter - Generic - FFT Forward
4. Result:
![ctd](https://github.com/rpeyron/plugin-gimp-fourier/assets/966048/595b22d7-bfde-4de6-a4a8-6a97bb642553)


Judging by the owner of the IP address (_CIDR: 204.79.196.0/23, 204.79.195.0/24, Organization: Microsoft Corporation (MSFT)_), the sending occurs due to Microsoft and its crash log analysis tools. But I still don’t understand why it is fourier.exe that initiates the connection.

**Comment by rpeyron** [comment]
Hello, thanks for the instructions to reproduce, but I am still unable to reproduce on my test VM. I have followed your instructions on a fresh Windows 10 x64, Gimp 2.10.32 and without internet access, and I don't observe any crash:

![image](https://github.com/rpeyron/plugin-gimp-fourier/assets/3126751/a44ca6a7-54fd-4d48-8071-75cb02bfca7d)

Are you able to test on a fresh setup / virtual machine?

**Comment by hhrhhr** [comment]
Unfortunately, it is not yet possible to do the experiment in a virtual machine. However, I noticed that the plugin crashes only in a certain case - when the selection does not include the upper left corner of the layer.
Attempts to access the Internet are really not related to the performance of the plugin, since without selection or with selection of the entire layer or its upper left corner the plugin works great.
Here is a short video that shows the behavior of the plugin with different types of selection. Maybe it will give you some ideas ;)

https://youtu.be/ps2wOmmOIjM

**Comment by rpeyron** [comment]
Hello, thank you for the video, I have managed to reproduce the bug. It seems it depends on the size and position of the selection/image. Once a failing setting is found, it is reproducible. And it seems it is not related with internet access, as it crashed the same way whether network is connected or not.  

Example of crashing settings: on image 300x300, selection 0,123-300,300  (regardless of the image contents)

I guess the internet access you see in the firewall is more a consequence of the crash (as Microsoft collects crash dumps) than the cause of the crash. 

Now I have a way to reproduce, I will be able to investigate. This may some time, I will update this bug when found. In the meantime, 

Thanks for reporting

**Comment by rpeyron** [comment]
Hello, 

I found the bug. The new release 0.4.5 should fix it. 

Thanks for reporting
